FOODIV-28 -Tela inicial com menu hamburguer
develcode-estagiarios-4/Develfood-Manoela pull request #12
Opened 2022-07-25 18:05 UTC by manoela-pereira-develcode

## Informações Jira

[FOODIV-28 -Tela inicial com menu hamburguer](https://develcode.atlassian.net/jira/software/c/projects/FOODIV/boards/22?modal=detail&selectedIssue=FOODIV-28)

## Checklists

### Antes do code review

- [ ] O nome da branch segue o padrão: feature/XXX-000, bugfix/XXX-000, hotfix/XXX-000 ou hotfix/erro-no-exemplo.
- [ ] O titulo da MR segue o padrão: XXX-000 - Adicionar Template de merge requests.
- [ ] Foi informado o link da task no Jira.
- [ ] A opção **Assign** na MR foi preenchida com o nome do responsável pela task.

### Após o code review

- [ ] A tipagem foi implementada corretamente sem o uso do tipo `any`, exceto quando necessário.
- [ ] Não foram acrescentados comentários `eslint-disable`, salvo se **realmente** necessário.
- [ ] Não foi feita **nenhuma** modificação no código que não estivesse prevista pela task no Jira informada nesta MR.
- [ ] Trechos de código comentados, que não estão sendo utilizados ou que não possuem uma previsão para serem utilizados foram removidos.
- [ ] Comentários desnecessários foram removidos.
- [ ] O revisor da task declara ter analisado todas as modificações de código e caminhos dos arquivos (salvo códigos e arquivos gerados automaticamente) e declara que está tudo apropriado e o nível de qualidade de código no projeto não foi reduzido.

#### **Observações sobre o checklist**

- Deve ser marcado **APENAS** pelo **REVISOR** da task.
- O revisor deve antes de fazer o code review, verificar se todos os pontos da checklist "Antes do code review" estão feitos. Caso negativo, o revisor deve pedir que o responsável (assign) revise-as primeiro antes de prosseguir.

2022-07-25 18:42 UTC, rafael-fachinelli-develcode requested changes
Melhorias de performance e postos de atenção.

2022-07-25 18:42 UTC, rafael-fachinelli-develcode commented on .eslintrc.json
> +        "no-plusplus": "off",
Recomendo dar uma olhada nessa página: https://eslint.org/docs/latest/rules/no-plusplus

Se pudermos evitar de desativar as regras é melhor. Mas se em alguma lógica ficar complicado, tudo bem.

2022-07-25 18:42 UTC, rafael-fachinelli-develcode commented on src/components/Container/index.tsx
> +export function Container({ children, active }: IContainer) {
Acredito que uma variável como setIsNavbarVisible possa ser mais semântica. Somente active não fica claro o que vamos ativar.

2022-07-25 18:42 UTC, rafael-fachinelli-develcode commented on src/components/EvaluationCard/style.module.scss
> +  background-color: #FAEEEE;
Não temos um arquivo com as variável de cores para o CSS?

2022-07-25 18:42 UTC, rafael-fachinelli-develcode commented on src/components/EvaluationCard/style.module.scss
> +  float: left;
Realmente é necessário o float? Geralmente resolvemos tudo com flexbox

2022-07-25 18:42 UTC, rafael-fachinelli-develcode commented on src/components/PromotionCard/index.tsx
> +const defautProps = {
a palavra default está faltando um L

2022-07-25 18:42 UTC, rafael-fachinelli-develcode commented on src/components/PromotionCard/index.tsx
> +PromotionCard.defaultProps = defautProps;
Faltando L no default

2022-07-25 18:42 UTC, rafael-fachinelli-develcode commented on src/components/StarRating/index.tsx
> +    gradePortion.push(parcialPainted * 10);
Geralmente evitamos utilizar o for, ele tem baixa perfomance comparada ao forEach

2022-07-25 18:42 UTC, rafael-fachinelli-develcode commented on src/hooks/useEvaluation.ts
> +      console.log(response.data);
Evite deixar console.log principalmente dos dados no código em repositório

2022-07-25 18:42 UTC, rafael-fachinelli-develcode commented on src/pages/Home/index.tsx
> +    }, 5000);
Nós temos a possiblidade de deixar mais lenta a conexão atravéz do devtools na aba network. Assim não precisa colocar esses timers no código para testar ou demonstrar

2022-07-25 18:42 UTC, rafael-fachinelli-develcode commented on src/pages/Home/index.tsx
> +  const pagesEvaluation: any = [];
realmente precisa ser any este array?

2022-07-25 18:42 UTC, rafael-fachinelli-develcode commented on src/pages/Home/index.tsx
> +    for (let i = 0; i < totalPagesEvaluation; i++) {
Não utilizar o for, utilizar forEach

2022-07-25 18:47 UTC, manoela-pereira-develcode commented on src/hooks/useEvaluation.ts
> +      console.log(response.data);
removido

2022-07-25 18:48 UTC, manoela-pereira-develcode commented on src/components/PromotionCard/index.tsx
> +const defautProps = {
Alterado

2022-07-25 18:48 UTC, manoela-pereira-develcode commented on src/pages/Home/index.tsx
> +  const pagesEvaluation: any = [];
Alterado para number[]

2022-07-25 18:57 UTC, manoela-pereira-develcode commented on src/pages/Home/index.tsx
> +    }, 5000);
Esse estado usei pois assim é possível carregar o ícone da estrela. Eu preciso pintar a estrela de maneira gradiente e só consegui usando ícones do google e de inicio, as vezes, eles aparecem inicialmente "STAR STAR STAR" para então aparecer de fato o ícone. Até a div que contem este o componente do skeleton esta com position absolute e z-index maior do que 1. assim não dando margem de o layout do ícone aparecer errado de início. Neste caso, também conseguimos arrumar na devtools?

2022-07-25 19:00 UTC, manoela-pereira-develcode commented on src/components/PromotionCard/index.tsx
> +PromotionCard.defaultProps = defautProps;
alterado

2022-07-25 19:03 UTC, manoela-pereira-develcode commented on src/components/Container/index.tsx
> +export function Container({ children, active }: IContainer) {
alterado para setIsNavbarInvisible

2022-07-25 19:05 UTC, manoela-pereira-develcode commented on src/components/EvaluationCard/style.module.scss
> +  background-color: #FAEEEE;
alterado. Criado $beige

2022-07-25 19:18 UTC, manoela-pereira-develcode commented on .eslintrc.json
> +        "no-plusplus": "off",
Alterado "++" para  "+= 1"  e excluído a regra desabilitada.

2022-07-26 12:47 UTC, rafael-fachinelli-develcode commented on src/pages/Home/index.tsx
> +    }, 5000);
E se usar um skelethon para exibir a imagem das estrelas somente após ter os dados?

2022-07-26 14:43 UTC, manoela-pereira-develcode commented on src/components/StarRating/index.tsx
> +    gradePortion.push(parcialPainted * 10);
alterado. Usado **Array.from({ length: fullPainted }).map((_, index: number) =**>

2022-07-26 14:48 UTC, manoela-pereira-develcode commented on src/components/EvaluationCard/style.module.scss
> +  float: left;
usado flexbox e excluído o float

2022-07-29 17:48 UTC, merged