Feat/foodiv 68
develcode-estagiarios-4/Develfood-Manoela pull request #2
Opened 2022-05-16 19:11 UTC by manoela-pereira-develcode

2022-05-16 19:26 UTC, juliana-develcode requested changes
Alguns ajustes e considerações.

2022-05-16 19:26 UTC, juliana-develcode commented on src/components/Container/index.tsx
> +    </div>
Realmente é necessário a div? Não podemos deixar o dragment?

2022-05-16 19:26 UTC, juliana-develcode commented on src/components/Botao/index.tsx
> +  onClick: (event: any) => void;
Utilizar o seguinte tipo para o event:

`React.ChangeEvent<HTMLInputElement>`

Vamos tentar evitar ao máximo o uso de any

2022-05-16 19:26 UTC, juliana-develcode commented on src/components/Input/index.tsx
> +  onChange: (event: any) => void;
Substituir o any pelo formato:

`React.ChangeEvent<HTMLInputElement>`

2022-05-16 19:26 UTC, juliana-develcode commented on src/components/Navbar/index.tsx
> +          </Link>
Acredito que este link, possa ser um componente chamado por exemplo: NavbarItem

Pois ele se repete bastante no código

2022-05-16 19:26 UTC, juliana-develcode commented on src/components/SpanInput/index.tsx
> +export default function Input2({
O nome está como Input2, talvez deveria ser SpanInput? Mesmo assim, não me parece um nome muito claro do que significa esse componente. Onde ele é usado? Essa pergunta pode ajudar para crirar um nome mais interessante.

2022-05-16 19:26 UTC, juliana-develcode commented on src/hooks/useLogin.ts
> +  password: any;
Acredito que o formato correto seria String

2022-05-17 12:07 UTC, manoela-pereira-develcode commented on src/hooks/useLogin.ts
> +  password: any;
alterado

2022-05-17 12:08 UTC, manoela-pereira-develcode commented on src/components/SpanInput/index.tsx
> +export default function Input2({
Este era um arquivo que usei para testar algumas coisas. Excluído já

2022-05-17 16:29 UTC, manoela-pereira-develcode commented on src/components/Container/index.tsx
> +    </div>
alterado

2022-05-17 16:44 UTC, manoela-pereira-develcode commented on src/components/Input/index.tsx
> +  onChange: (event: any) => void;
alterado

2022-05-18 17:05 UTC, merged